### ISSUE TITLE
Question: What Causes 429 Too Many Requests Error?

### ISSUE THREAD

**Issue by capk1rk** [duosecurity/duo_client_python#101]
Occasionally I receive a 429 error from Duo and I haven't been able to find a specific limit in the docs. What, if any, are the request limits? And does the python package have a retry method?

**Comment by AaronAtDuo** [comment]
@capk1rk We've recently added rate limiting to API calling.  I'll get back to you with some information on what the rate limits are, but can I ask what version of the client library you're using?  There was a change made (commit b4a40abc7d5a72bfc3c4f3656619511390c97220, March 9, released in version 4.2.0) that automatically handles the rate limiting for the caller.

**Comment by AaronAtDuo** [comment]
Some default rate limits for the most common uses of the API client are:
- AdminAPI modify object rate limit: 300 requests/min
- AdminAPI get single object rate limit: 300 requests/min
- AdminAPI get page of objects rate limit: 200 requests/min
- AdminAPI get all objects rate limit (no paging): 40 requests/min
- Authentication logs: 2 requests/min
- Telephony logs: 2 requests/min
- Administrator Action logs: 2 requests/min

Your best bet is to use version 4.2.0 or later of the client as I noted before.  Per https://help.duo.com/s/article/1338?language=en_US:
> If you are using a Duo-supported client library, updating to the newest version of the library available should resolve this issue as the client will back off automatically and make requests within the limit.

If you have a specific need for a higher rate limit, please contact our support organization (https://duo.com/support).

Hopefully this information answers your question.  Please let us know if there's any other information about the rate limiting we can provide, and thanks for using Duo!

**Comment by capk1rk** [comment]
We are on the latest version of the client. It was working great for a while until we saw a big spike in traffic. Then it broke down a handful of times. I just wanted to double check what the specific rate limiting was so that we could stay under it. Thanks
