### ISSUE TITLE
Support for Trust Monitor Data

### ISSUE THREAD

**Issue by rootshellz** [duosecurity/duo_client_python#135]
I would like support for [Trust Monitor Data](https://duo.com/docs/trust-monitor#trust-monitor-data) by implementing the [trust_monitor endpoint](https://duo.com/docs/adminapi#trust-monitor).

**Comment by DuoKristina** [comment]
Thanks you for this feedback. We'll take a look at updating the API examples.

If your use case for our Admin API is to pull logs/auth/trust data, have you taken a look at the [duologsync](https://github.com/duosecurity/duo_log_sync) tool? This is a standalone Python 3 utility that already includes support for the trust monitor endpoints (among others).

**Comment by nomadmtb** [comment]
Hi @rootshellz!  The existing client should have functionality to pull Trust Monitor events from your Admin API integration.  I do agree with @DuoKristina that there should probably be some more explicit examples for this, but in the meantime you can you the following methods if you wanted to give it another shot.

```
from duo_client import Admin


admin_client = Admin("<your ikey>", "<your skey>", "<your api-hostname>")


admin_client.get_trust_monitor_events_by_offset
admin_client.get_trust_monitor_events_iterator
```

https://github.com/duosecurity/duo_client_python/blob/34c165c3a74ec791c5e2079872b8dceba14e3d5d/duo_client/admin.py#L2880

https://github.com/duosecurity/duo_client_python/blob/34c165c3a74ec791c5e2079872b8dceba14e3d5d/duo_client/admin.py#L2921

**Comment by nomadmtb** [comment]
Posted a PR above that supplies a sample-script that can show other folks how to fetch Trust Monitor events from the Admin API.
