### ISSUE TITLE
Client sends two `Host` headers

### ISSUE THREAD

**Issue by gkelly** [duosecurity/duo_client_python#143]
It appears that the `Client` erroneously sends two `Host` headers during requests:

```
GET /auth/v2/ping? HTTP/1.1\r
Host: localhost\r
Accept-Encoding: identity\r
Authorization: Basic aWtleTphMTNiMDcwYzI4MmU3NDY0NDEwYWZkYjdmZGQ2YWY0MDc3OGM1Zjcw\r
Date: Wed, 19 May 2021 01:46:41 -0000\r
Host: localhost\r
User-Agent: Duo API Python/4.3.1\r
\r
```

**Comment by AaronAtDuo** [comment]
@gkelly Can you confirm you are using Python 3?  I can replicate this issue with Python 3.8.5 but not with 2.7.18.  On Python 2 I get only one Host header.  If possible, could you see if you get the same result for Python 2?

**Comment by gkelly** [comment]
Yes, I am using Python 3. I just tested this in Python 2.7.14 and did not see the same double-Host-header behavior. However, I also tested #145 in Python 2.7.14 and it does not remove the lone `Host` header. That is, the request looks correct with the patch applied:

```
POST /auth/v2/auth HTTP/1.1\r
Host: localhost\r
Accept-Encoding: identity\r
Content-Length: 22\r
Date: Wed, 02 Jun 2021 19:15:49 -0000\r
Content-type: application/x-www-form-urlencoded\r
Authorization: Basic <removed>\r
User-Agent: Duo API Python/4.3.1\r
\r
async=1&factor=testing
```

**Comment by AaronAtDuo** [comment]
I agree.  So it seems the Py2 behavior of HTTPConnection is:
"Add a Host header _if it's not already there_"
Where Py3 is
"Add a Host header"

**Comment by AaronAtDuo** [comment]
Merged!  We'll try to get a release done ASAP.

Thanks for the contribution and thanks for using Duo.
