### ISSUE TITLE
Add Support Create Integration for SSO type

### ISSUE THREAD

**Issue by vennemp** [duosecurity/duo_client_python#162]
Please add API endpoints for DUO SSO integration automation. Currently only DAG is supported and you are EOL the DAG this month.

**Comment by AaronAtDuo** [comment]
@vennemp I am working with our internal SSO developers on a PR to add this:
https://github.com/duosecurity/duo_client_python/pull/165

Is that what you are looking for?

**Comment by AaronAtDuo** [comment]
@vennemp This has been added by commit https://github.com/duosecurity/duo_client_python/commit/42a5a1dc58cd5f5304ceb87d704c4a863011bd5d and is included in the 4.6.0 release just done today.

**Comment by AaronAtDuo** [comment]
We had to revert this in 4.6.1 due to a bug. but it will return soon

**Comment by AaronAtDuo** [comment]
This returned in 4.7.0.
