### ISSUE TITLE
No wheel distributions for Python 3.

### ISSUE THREAD

**Issue by eikonomega** [duosecurity/duo_client_python#17]
Hey All,
Your TravisCI config looks like you test against Python 3.3/3.4 but you aren't publishing and Python3 wheels to PyPI.  This makes you have to monkey with the wheel filename to install on Python 3 and gives the sense that what you are doing isn't supported.

Maybe your library is only Python2... but since you are testing on 3, I'm hoping maybe you just need to change your distribution settings a tiny bit.

https://pypi.python.org/pypi/duo_client/3.0

Cheers.

**Comment by mschwager** [comment]
Hey, thanks for the heads up! I've fixed the issue in this (https://github.com/duosecurity/duo_client_python/commit/1cc71f80927b02e75773094c9dd77af1fc8e4064) commit, and uploaded the resulting package to pypi. Can you confirm?

**Comment by eikonomega** [comment]
Sure.  Out of the office today, but will confirm on Monday.
Awesome!

On Fri, Oct 30, 2015 at 9:53 AM mschwager <notifications@github.com> wrote:

> Hey, thanks for the heads up! I've fixed the issue in this (1cc71f8
> <https://github.com/duosecurity/duo_client_python/commit/1cc71f80927b02e75773094c9dd77af1fc8e4064>)
> commit, and uploaded the resulting package to pypi. Can you confirm?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duosecurity/duo_client_python/issues/17#issuecomment-152531527>
> .
>
-- 
------------------------------------------------
Mike Dunn
https://about.me/eikonomega

Returning hate for hate multiplies hate, adding deeper darkness to a night
already devoid of stars. Darkness cannot drive out darkness; only light can
do that. Hate cannot drive out hate; only love can do that. - MLK

**Comment by mschwager** [comment]
Any luck?

**Comment by eikonomega** [comment]
Hey sorry.  Forgot.

Looks good!
>>> pip install duo_client
Collecting duo-client
  Downloading duo_client-3.0-py2.py3-none-any.whl
Collecting six (from duo-client)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting nose (from duo-client)
  Using cached nose-1.3.7-py3-none-any.whl
Installing collected packages: nose, six, duo-client

Successfully installed duo-client-3.0 nose-1.3.7 six-1.10.0

On Mon, Nov 2, 2015 at 1:18 PM mschwager <notifications@github.com> wrote:

> Any luck?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/duosecurity/duo_client_python/issues/17#issuecomment-153112262>
> .
>
-- 
------------------------------------------------
Mike Dunn
https://about.me/eikonomega

Returning hate for hate multiplies hate, adding deeper darkness to a night
already devoid of stars. Darkness cannot drive out darkness; only light can
do that. Hate cannot drive out hate; only love can do that. - MLK

**Comment by mschwager** [comment]
Great, thanks again!
