### ISSUE TITLE
"Invalid Integration key in request credentials"

### ISSUE THREAD

**Issue by skiptomyliu** [duosecurity/duo_client_python#26]
I am having difficulty just getting the examples to run.

I've had DUO enable the Admin API on our plan.  However, copying and pasting the integration key, secret key, and API hostname directly into the examples I am met with:

"RuntimeError: Received 401 Invalid integration key in request credentials"

Any additional steps that I am missing?

Thanks

**Comment by BradleyHiggins** [comment]
Enabling the Admin API allows you to create an Admin API Application type.  Once you create that, you must use the ikey/skey/apihost config from that Admin API Application to make Admin API calls.

**Comment by skiptomyliu** [comment]
Thank you, that was my misunderstanding.  I was under the impression that the enabling automatically allowed the usage of the API with no further steps.  I was using the ikey,skey,apihost on our existing apps.  

Creating the "Admin API" application type on DUO resolved this.  Thanks.
