### ISSUE TITLE
Question - How to properly use add_yubikey_token

### ISSUE THREAD

**Issue by mrSpartonRose** [duosecurity/duo_client_python#273]
I am working on a program to "re-key" our Yubikey tokens. What I need to do is to recode the key, delete the old token in Duo, add the new token in Duo, and then reassociate the new token with the owners.

Does anyone have an example of how to use add_yubikey_token? Specifically how to generate the parameters that go into it.

Pseudocode looks like this ...

- Download all token info from the server
- Plug in the yubikey and get the info for that token
- Regenerate a new private id and secret key
- Program the yubikey with the new data (Works)
- delete the key from Duo
- Add the key with new data to Duo (Does not work - error below)
- Re associate new key with users

Code snippets are here...
```
for device in s.multi(allow_initial=True):
public_id = b"\xFF\x00" + struct.pack(b">I", device.info.serial)
serialModHex = modhex_encode(public_id);
private_id = os.urandom(6)
key = os.urandom(16)

YubiOtpSlotConfiguration(public_id, private_id, key).append_cr(True)

newToken = duoComm.add_yubikey_token ( serial=serialModHex,
                                        private_id=private_id,
                                        aes_key=key  )
```

Error: Object of type bytes is not JSON serializable

**Comment by mrSpartonRose** [comment]
```
duoComm.add_user_token(user_id=user['username'],
                                       token_id=modhex_encode(newToken['token_id']),
                                       aes_key=modhex_encode(key))
```

I tried using modehex_encode as well, and that did not work either. When I do this I get the following error.

Received 400 Invalid request parameters (private_id)

**Comment by DuoKristina** [comment]
Verify you're sending the private_id value as 12 char hex and aes_key as 32 char hex to the Duo API.

**Comment by mrSpartonRose** [comment]
That appears to have done it! Here is the relevant code ...

```
private_id = os.urandom(6)
key = os.urandom(16)

private_id_hex=''.join(format(x, '02x') for x in private_id)
aes_key_hex=''.join(format(x, '02x') for x in key)

newToken = duoComm.add_yubikey_token ( serial=foundSerial,
                                        private_id=private_id_hex,
                                        aes_key=aes_key_hex)
```

**Comment by DuoKristina** [comment]
TY - I notice the API doc doesn't specify hex so we will update that.
