### ISSUE TITLE
'async' is a reserved keyword in Python 3.7

### ISSUE THREAD

**Issue by mschwager** [duosecurity/duo_client_python#41]
Basically, `async` is now a reserved keyword in Python 3.7, similar to `return` or `def` in earlier versions. The `duo_client` library makes use of `async` as a keyword argument in a few locations, namely `duo_client/auth.py` and `duo_client/auth_v1.py`, which causes a `SyntaxError` on Python 3.7:

```
ImportError: Failed to import test module: tests.test_client
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/nose2/plugins/loader/discovery.py", line 201, in _find_tests_in_file
    module = util.module_from_name(module_name)
  File "/home/travis/virtualenv/python3.7-dev/lib/python3.7/site-packages/nose2/util.py", line 77, in module_from_name
    __import__(name)
  File "/home/travis/build/duosecurity/duo_client_python/tests/test_client.py", line 4, in <module>
    import duo_client.client
  File "/home/travis/build/duosecurity/duo_client_python/duo_client/__init__.py", line 4, in <module>
    from .auth import Auth
  File "/home/travis/build/duosecurity/duo_client_python/duo_client/auth.py", line 115
    async=False,
        ^
SyntaxError: invalid syntax
```

TravisCI is catching this as well: https://travis-ci.org/duosecurity/duo_client_python/jobs/336651090

Python 3.7 is expected to come out sometime in the middle of 2018 (https://www.python.org/dev/peps/pep-0537/#schedule), we should probably fix this error before then. It's worth noting that this change will most likely require breaking changes, and for consumers to update their code to use the new keyword argument.

PEP 8 recommends appending a `_` to make the keyword argument `async_`: https://www.python.org/dev/peps/pep-0008/#function-and-method-arguments

**Comment by mschwager** [comment]
Side note: it may be worthwhile to allow failures on Python 3.7 on TravisCI for now (https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail). Since that version hasn't been officially released yet it seems sane to not prioritize working on it, and not block green builds on that work.

**Comment by sontek** [comment]
Just ran into this while upgrading our releases to 3.7.   Can we get a new release?

**Comment by gettes** [comment]
Yes, another vote for getting this fixed for 3.7 and the need to support alias1-4 for users objects, please!!

**Comment by jholt13** [comment]
Adding another voice to this, an updated library for Python3.7 would be appreciated.

**Comment by gettes** [comment]
Yes, not only the alias1..4 support on update but 3.7 as well.  I believe the issue is ‘async’ is reserved.  We run python apps in Docker containers and use the latest version of python so this too is needed.

Thanks!

/mrg

**Comment by AaronAtDuo** [comment]
https://github.com/duosecurity/duo_client_python/pull/59 is up to resolve this.  Hope to merge it soon!

**Comment by AaronAtDuo** [comment]
My team has merged the PR, this issue should be resolved.  Please let us know if there's any problems.

**Comment by taras-rudnyk-exa** [comment]
@AaronAtDuo, thanks for fixing this issue. Could you please upload new version (4.0.0) to PyPI?

**Comment by AaronAtDuo** [comment]
Sure thing.  Sorry it got overlooked.  We'll try to get that updated shortly.

**Comment by onkarnewgen** [comment]
Rename 'async' to anything else on each place in auth.py It will work fine
