### ISSUE TITLE
Upload to the Python Packaging Index

### ISSUE THREAD

**Issue by mgedmin** [duosecurity/duo_client_python#5]
It would be incredibly convenient if you would upload this library to the Python Package Index.

In case you're not familiar with PyPI, all you have to do is register for an account at https://pypi.python.org/pypi, then check out duo_client_python and run

    python setup.py sdist register upload

This will ask for your PyPI username and password and remember them in ~/.pypirc, so that future uploads don't need to ask for it again.

Advantages of having your package published in PyPI are:
* people can find it
* people can install it by running `pip install duo_client`
* people who write libraries or applications can include it in their dependency lists by name

**Comment by RyanFolsom** [comment]
+1

**Comment by RyanFolsom** [comment]
+1

Looks like someone already put it up, not if it's official or not though.

**Comment by olivierpilotte** [comment]
Yes, it wasn't on their short term roadmap, so I've uploaded it with their authorization. Works for me, let me know if I can help you with anything.

**Comment by RyanFolsom** [comment]
That's perfect - thank you!

**Comment by mschwager** [comment]
https://pypi.python.org/pypi/duo_client/2.1
