### ISSUE TITLE
Could not find a version that satisfies the requirement duo_client

### ISSUE THREAD

**Issue by ghost** [duosecurity/duo_client_python#80]
C:\Users\mschloss\Python\duo_client_python-master>C:\Python27\Scripts\pip.exe install duo_client
Collecting duo_client
  Could not find a version that satisfies the requirement duo_client (from versions: )
No matching distribution found for duo_client

Windows 10
Python 2.7
Pip or Pip2 9.0.3

**Comment by AaronAtDuo** [comment]
Closing out this old issue.
