### ISSUE TITLE
paging limit / offset error

### ISSUE THREAD

**Issue by mricharf** [duosecurity/duo_client_python#87]
I have code working on v.3 of the duo_client scripts. Bringing it up to v4, I'm receiving the following errors. The same error occurs with the user export script from the 'examples' directory. I just sync'd the new admin.py that was updated a little while ago.

`<pre>-bash-4.1$ ./test_userdump.py
 
Admin API integration key ("DI..."): MY INTEGRATION KEY
integration secret key: MY SECRET KEY
API hostname ("api-....duosecurity.com"): MY API URL
Traceback (most recent call last):
  File "./test_userdump.py", line 25, in <module>
    users = admin_api.get_users()
  File "/path/to/admin.py", line 522, in get_users
    (limit, offset) = self.normalize_paging_args(limit, offset)
  File "/path/to/client.py", line 347, in normalize_paging_args
    offset = '{}'.format(offset)
ValueError: zero length field name in format</pre>`

**Comment by duopeter** [comment]
Are you using something earlier than python 2.7 by any chance?  Just something to check...I don't think that use of format was supported until 2.7.

**Comment by mricharf** [comment]
I was using the OS default of 2.6. I installed 3.4 and changed my script, and it appears to be working. Thanks!
