### ISSUE TITLE
admin-logs is failing randomly

### ISSUE THREAD

**Issue by arangyupgrade** [duosecurity/duo_client_python#91]
I'm using this `lambda_handler.py' with the latest `duo-client` package on kubernetess and now I'm seeing the handler is failing randomly because of this error:

```
dumping logs
dumped successfully.
Retrieved admin Logs.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/sumologic-duo-security/lambda_function.py", line 102, in lambda_handler
    logs_admin = format_admin_logs(logs_admin)
  File "/opt/sumologic-duo-security/lambda_function.py", line 65, in format_admin_logs
    for ph in (i['description']['phones']):
TypeError: 'NoneType' object is not iterable
```
The handler could not fetch `admin_logs`

because this issue is happening randomly I guess there is a bug in the code
thanks

**Comment by DuoKristina** [comment]
Is there any error output that tells you why it can't fetch the logs? The Duo API should return something.

We've made some changes to our Admin API lately so it's possible that sumologic-duo-security script needs updates as well. In particular, I don't see any use of our paging parameters in that lambda script. I suggest you open an issue for the maintainer of that repository.

**Comment by AaronAtDuo** [comment]
Closing this old issue
