### ISSUE TITLE
No module named 'duo_client'

### ISSUE THREAD

**Issue by HemanthVikash** [duosecurity/duo_client_python#93]
Traceback (most recent call last):
  File "report_users_and_phones.py", line 7, in <module>
    import duo_client
ModuleNotFoundError: No module named 'duo_client'

**Comment by xdesai** [comment]
Hello,
I'm making an assumption that you ran
```
$ python report_users_and_phones.py
```
let me know if this is not the command you ran before getting this error.

The error you are reporting mostly likely means the duo_client library isn't properly installed on your system. Can you give these steps a try and let me know if it works for you?
Note: The first two steps are about creating a python environment to run in. You may need to pip install virtualenv if you don't have it already
```
$ virtualenv venv
$ source venv/bin/activate
$ pip install duo_client
$ python /path/to/examples_folder/report_users_and_phones.py
```

**Comment by vbscott** [comment]
Hello, it looks like this PR is solved so I am going to close this out.
